"""Initial database schema

Revision ID: 96782474bacd
Revises: 
Create Date: 2025-06-24 06:45:23.487418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96782474bacd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 